Resources:
  letsPollLambdaBasicExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "LetsPollLambdaBasicExecutionPolicyRenamed"
      PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: logs:CreateLogGroup
              Resource: arn:aws:logs:${self:provider.region}:#{AWS::AccountId}::*
            - Effect: Allow
              Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource:
              - arn:aws:logs:#{AWS::AccountId}:log-group:/aws/lambda/${self:service.name}-${self:provider.stage}-logGroup:*
      Roles:
          -
            Ref: letsPollLambdaExecutionRole
