Resources:
  LambdaInVPCExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "LambdaInVPCExecutionPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
          Resource: "*"
      Roles:
          -
            Ref: letsPollLambdaExecutionRole
